# Core tools referenced directly by this repository's shell, editor, terminal,
# multiplexer, and agent configuration.
tap "griffinqiu/tap"

brew "bash"
brew "bun"
brew "coreutils"
brew "diff-so-fancy"
brew "fd"
brew "fzf"
brew "gawk"
brew "git"
brew "git-lfs"
brew "gh"
brew "glab"
brew "herdr"
brew "jq"
brew "lazygit"
brew "macvim"
brew "mise"
brew "neovim"
brew "rcm"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "tmux"
brew "universal-ctags"
brew "uv"
brew "zoxide"
brew "griffinqiu/tap/bootmux"

cask "1password-cli"
cask "font-hack-nerd-font"
cask "ghostty"
