#!/bin/bash

echo "      _       _      __ _ _"
echo "   __| | ___ | |_   / _(_) | ___  ___"
echo "  / _\` |/ _ \| __| | |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||  |  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__| |_| |_|_|\___||___/"
echo ""

brew bundle --file=- <<EOF
brew "tig"
brew "ncdu"
brew "diff-so-fancy"
brew "stress"
brew "watch"
brew "sysbench"
brew "neovim", args: ["HEAD"]
cask "homebrew/cask-fonts/font-hack-nerd-font"
EOF

if [ ! -e "$HOME"/.oh-my-zsh ]; then
    echo 'Installing oh-my-zsh'
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

if [ ! -e "$HOME"/.tmux ]; then
    echo 'Installing tpm'
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
    "$HOME/.tmux/plugins/tpm/bin/install_plugins"
fi

if [ ! -e "$HOME"/tmp ]; then
    mkdir -p "$HOME"/tmp
fi

if [ ! -e "$HOME"/tmp/tags ]; then
    mkdir -p "$HOME"/tmp/tags
fi

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  nvim -E -s +PlugUpgrade +qa
else
  echo 'Initing plug.vim'
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +PlugUpdate +PlugClean! +qa

reset -Q
