#!/bin/bash

echo "      _       _      __ _ _"
echo "   __| | ___ | |_   / _(_) | ___  ___"
echo "  / _\` |/ _ \| __| | |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||  |  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__| |_| |_|_|\___||___/"
echo ""

brew bundle --file=- <<EOF
brew "tig"
brew "ncdu"
brew "diff-so-fancy"
brew "stress"
brew "watch"
# brew "sysbench"
brew "macvim"
brew "neovim", args: ["HEAD"]
cask "homebrew/cask-fonts/font-hack-nerd-font"
EOF

if [ ! -e "$HOME"/.oh-my-zsh ]; then
    echo 'Installing oh-my-zsh'
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

if [ ! -e "$HOME"/.tmux ]; then
    echo 'Installing tpm'
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
    "$HOME/.tmux/plugins/tpm/bin/install_plugins"
fi

if [ ! -e "$HOME"/tmp ]; then
    mkdir -p "$HOME"/tmp
fi

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  nvim -E -s +PlugUpgrade +qa
else
  echo 'Initing plug.vim'
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
nvim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa
nvim +"CocInstall -sync coc-json coc-tsserver coc-html coc-css coc-vetur coc-solargraph coc-highlight coc-prettier" +qa

reset -Q

# detect old OS X broken /etc/zshenv and suggest rename
if grep -qw path_helper /etc/zshenv 2>/dev/null; then
  dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

  cat <<MSG >&2
Warning: \`/etc/zshenv' configuration file on your system may cause unexpected
PATH changes on subsequent invocations of the zsh shell. The solution is to
rename the file to \`zprofile':
  sudo mv /etc/{zshenv,zprofile}

(called from ${dir}/post-up:${LINENO})

MSG
fi
